# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create!(name: "lemon")
Ingredient.create!(name: "ice")
Ingredient.create!(name: "mint leaves")
Ingredient.create!(name: "Light rum")
Ingredient.create!(name: "Applejack")
Ingredient.create!(name: "Gin")
Ingredient.create!(name: "Dark rum")
Ingredient.create!(name: "Sweet Vermout")
Ingredient.create!(name: "Strawberry schnapps")
Ingredient.create!(name: "Scotch")
Ingredient.create!(name: "Apricot brandy")
Ingredient.create!(name: "Triple sec")
Ingredient.create!(name: "Southern Comfort")
Ingredient.create!(name: "Orange bitters")
Ingredient.create!(name: "Brandy")
Ingredient.create!(name: "Lemon vodka")
Ingredient.create!(name: "Blended whiskey")
Ingredient.create!(name: "Dry Vermouth")
Ingredient.create!(name: "Amaretto")
Ingredient.create!(name: "Tea")
Ingredient.create!(name: "Champagne")
Ingredient.create!(name: "Coffee liqueur")
Ingredient.create!(name: "Bourbon")
Ingredient.create!(name: "Tequila")
